// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/config_audit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigAuditService_AuditConfig_FullMethodName   = "/config_audit.ConfigAuditService/AuditConfig"
	ConfigAuditService_GetServerInfo_FullMethodName = "/config_audit.ConfigAuditService/GetServerInfo"
)

// ConfigAuditServiceClient is the client API for ConfigAuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigAuditServiceClient interface {
	AuditConfig(ctx context.Context, in *AuditConfigRequest, opts ...grpc.CallOption) (*AuditConfigResponse, error)
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfo, error)
}

type configAuditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigAuditServiceClient(cc grpc.ClientConnInterface) ConfigAuditServiceClient {
	return &configAuditServiceClient{cc}
}

func (c *configAuditServiceClient) AuditConfig(ctx context.Context, in *AuditConfigRequest, opts ...grpc.CallOption) (*AuditConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditConfigResponse)
	err := c.cc.Invoke(ctx, ConfigAuditService_AuditConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configAuditServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfo)
	err := c.cc.Invoke(ctx, ConfigAuditService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigAuditServiceServer is the server API for ConfigAuditService service.
// All implementations must embed UnimplementedConfigAuditServiceServer
// for forward compatibility.
type ConfigAuditServiceServer interface {
	AuditConfig(context.Context, *AuditConfigRequest) (*AuditConfigResponse, error)
	GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfo, error)
	mustEmbedUnimplementedConfigAuditServiceServer()
}

// UnimplementedConfigAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigAuditServiceServer struct{}

func (UnimplementedConfigAuditServiceServer) AuditConfig(context.Context, *AuditConfigRequest) (*AuditConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditConfig not implemented")
}
func (UnimplementedConfigAuditServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedConfigAuditServiceServer) mustEmbedUnimplementedConfigAuditServiceServer() {}
func (UnimplementedConfigAuditServiceServer) testEmbeddedByValue()                            {}

// UnsafeConfigAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigAuditServiceServer will
// result in compilation errors.
type UnsafeConfigAuditServiceServer interface {
	mustEmbedUnimplementedConfigAuditServiceServer()
}

func RegisterConfigAuditServiceServer(s grpc.ServiceRegistrar, srv ConfigAuditServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigAuditService_ServiceDesc, srv)
}

func _ConfigAuditService_AuditConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAuditServiceServer).AuditConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAuditService_AuditConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAuditServiceServer).AuditConfig(ctx, req.(*AuditConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigAuditService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigAuditServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigAuditService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigAuditServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigAuditService_ServiceDesc is the grpc.ServiceDesc for ConfigAuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigAuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config_audit.ConfigAuditService",
	HandlerType: (*ConfigAuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuditConfig",
			Handler:    _ConfigAuditService_AuditConfig_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _ConfigAuditService_GetServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/config_audit.proto",
}
