// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/config_audit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigData    []byte                 `protobuf:"bytes,1,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	ConfigFormat  string                 `protobuf:"bytes,2,opt,name=config_format,json=configFormat,proto3" json:"config_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditConfigRequest) Reset() {
	*x = AuditConfigRequest{}
	mi := &file_proto_config_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditConfigRequest) ProtoMessage() {}

func (x *AuditConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditConfigRequest.ProtoReflect.Descriptor instead.
func (*AuditConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditConfigRequest) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *AuditConfigRequest) GetConfigFormat() string {
	if x != nil {
		return x.ConfigFormat
	}
	return ""
}

type Finding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Severity       string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Rule           string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Recommendation string                 `protobuf:"bytes,4,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Path           string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_proto_config_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_proto_config_audit_proto_rawDescGZIP(), []int{1}
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *Finding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	High          int32                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	Medium        int32                  `protobuf:"varint,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Low           int32                  `protobuf:"varint,4,opt,name=low,proto3" json:"low,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_proto_config_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_proto_config_audit_proto_rawDescGZIP(), []int{2}
}

func (x *Summary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Summary) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Summary) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *Summary) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

type AuditConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*Finding             `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	Summary       *Summary               `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditConfigResponse) Reset() {
	*x = AuditConfigResponse{}
	mi := &file_proto_config_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditConfigResponse) ProtoMessage() {}

func (x *AuditConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditConfigResponse.ProtoReflect.Descriptor instead.
func (*AuditConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditConfigResponse) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *AuditConfigResponse) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_proto_config_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_audit_proto_rawDescGZIP(), []int{4}
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_proto_config_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_proto_config_audit_proto_rawDescGZIP(), []int{5}
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_proto_config_audit_proto protoreflect.FileDescriptor

const file_proto_config_audit_proto_rawDesc = "" +
	"\n" +
	"\x18proto/config_audit.proto\x12\fconfig_audit\"Z\n" +
	"\x12AuditConfigRequest\x12\x1f\n" +
	"\vconfig_data\x18\x01 \x01(\fR\n" +
	"configData\x12#\n" +
	"\rconfig_format\x18\x02 \x01(\tR\fconfigFormat\"\x8f\x01\n" +
	"\aFinding\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0erecommendation\x18\x04 \x01(\tR\x0erecommendation\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"]\n" +
	"\aSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x05R\x04high\x12\x16\n" +
	"\x06medium\x18\x03 \x01(\x05R\x06medium\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x05R\x03low\"y\n" +
	"\x13AuditConfigResponse\x121\n" +
	"\bfindings\x18\x01 \x03(\v2\x15.config_audit.FindingR\bfindings\x12/\n" +
	"\asummary\x18\x02 \x01(\v2\x15.config_audit.SummaryR\asummary\"\x16\n" +
	"\x14GetServerInfoRequest\"I\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName2\xb7\x01\n" +
	"\x12ConfigAuditService\x12R\n" +
	"\vAuditConfig\x12 .config_audit.AuditConfigRequest\x1a!.config_audit.AuditConfigResponse\x12M\n" +
	"\rGetServerInfo\x12\".config_audit.GetServerInfoRequest\x1a\x18.config_audit.ServerInfoB&Z$github.com/BurtsE/config-audit/protob\x06proto3"

var (
	file_proto_config_audit_proto_rawDescOnce sync.Once
	file_proto_config_audit_proto_rawDescData []byte
)

func file_proto_config_audit_proto_rawDescGZIP() []byte {
	file_proto_config_audit_proto_rawDescOnce.Do(func() {
		file_proto_config_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_audit_proto_rawDesc), len(file_proto_config_audit_proto_rawDesc)))
	})
	return file_proto_config_audit_proto_rawDescData
}

var file_proto_config_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_config_audit_proto_goTypes = []any{
	(*AuditConfigRequest)(nil),   // 0: config_audit.AuditConfigRequest
	(*Finding)(nil),              // 1: config_audit.Finding
	(*Summary)(nil),              // 2: config_audit.Summary
	(*AuditConfigResponse)(nil),  // 3: config_audit.AuditConfigResponse
	(*GetServerInfoRequest)(nil), // 4: config_audit.GetServerInfoRequest
	(*ServerInfo)(nil),           // 5: config_audit.ServerInfo
}
var file_proto_config_audit_proto_depIdxs = []int32{
	1, // 0: config_audit.AuditConfigResponse.findings:type_name -> config_audit.Finding
	2, // 1: config_audit.AuditConfigResponse.summary:type_name -> config_audit.Summary
	0, // 2: config_audit.ConfigAuditService.AuditConfig:input_type -> config_audit.AuditConfigRequest
	4, // 3: config_audit.ConfigAuditService.GetServerInfo:input_type -> config_audit.GetServerInfoRequest
	3, // 4: config_audit.ConfigAuditService.AuditConfig:output_type -> config_audit.AuditConfigResponse
	5, // 5: config_audit.ConfigAuditService.GetServerInfo:output_type -> config_audit.ServerInfo
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_config_audit_proto_init() }
func file_proto_config_audit_proto_init() {
	if File_proto_config_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_audit_proto_rawDesc), len(file_proto_config_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_audit_proto_goTypes,
		DependencyIndexes: file_proto_config_audit_proto_depIdxs,
		MessageInfos:      file_proto_config_audit_proto_msgTypes,
	}.Build()
	File_proto_config_audit_proto = out.File
	file_proto_config_audit_proto_goTypes = nil
	file_proto_config_audit_proto_depIdxs = nil
}
